[toolchain]

[features]
seeds = true
skip-lint = false

[programs.devnet]
counter = "7FBBdRPMWb7eE5pRdpi3GRCNjxwFNwv33BGz3PNHb4bt"

[programs.localnet]
counter = "GTGJSUboHkvLJmRhjzFxdhNdetg8Gu47wRuDVrW14zhU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
